
version: '3.0'
services:
  web:
    build: .
    ports:
      - "80:80"
    links:
      - db
    env_file:
      - env
    volumes:
      - ./zaapko:/var/www/html
      - ./conf/php.ini:/usr/local/etc/php/php.ini
      - ./conf/vhosts:/etc/apache2/sites-enabled
  db:
    image: mysql:5.6.23
    volumes:
      - ./data-mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8580:80"
    links:
      - db
