version: '3.9'
services:
    php:
        # image: 'php:7.2-fpm'
        build:
            context: ./docker
            dockerfile: php.Dockerfile
        container_name: ${APP_NAME:?err}-php
        user: "${UID}:${GID}"
        volumes:
            - './app:/var/www/html'

    nginx:
        image: nginx:latest
        container_name: ${APP_NAME:?err}-nginx
        user: "${UID}:${GID}"
        ports:
            - '8082:80'
            - '443:443'
        links:
            - 'php'
        volumes:
            - './app:/var/www/html'
            - './config/nginx:/etc/nginx/conf.d'

    pma:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
        ports:
            - 8303:80
        links:
            - mariadb:db

    mariadb:
        image: mariadb:10.3.38
        container_name: ${APP_NAME:?err}-mariadb
        restart: 'on-failure'
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
        ports:
            - '3306:3306'
        volumes:
            - ${PWD}/mariadb:/var/lib/mysql
